server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: tempeh-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: tempeh
          __path__: /var/log/tempeh/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: ts
            level: level
            component: component
            message: msg
      - labels:
          level:
          component:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message
